component: scf
name: resizing-scf
org: jason-tencent
app: resizing-app
stage: dev
inputs:
  name: ${name}
  src: ./
  description: >-
    This demo need to config COS trigger. When object has been upload to COS
    bucket, the SCF will download it to /tmp and compress it. 本示例配置了 COS
    触发器，当有文件上传到对应的 COS bucket时，会触发云函数执行，并把文件下载到本地临时目录，用做后续处理
  handler: Thumbnail.main_handler
  runtime: Python2.7
  namespace: default
  region: ${env:region}
  environment:
    variables:
        appid: ${env:appid}
        secret_id: ${env:TENCENT_SECRET_ID}
        secret_key: ${env:TENCENT_SECRET_KEY}
        region: ${env:region}
        resized_bucket: ${env:resized_bucket}
  memorySize: 128
  timeout: 5
  events:
     - cos: # cos触发器
        name: ${output:${stage}:${app}:cos-bucket.cosOrigin}
        parameters:
          bucket: ${output:${stage}:${app}:cos-bucket.cosOrigin}
          filter:
            prefix:
            suffix:
          events: cos:ObjectCreated:*
          enable: true
