component: cos
name: cos-bucket
org: jason-tencent
app: resizing-app
stage: dev

inputs:
  bucket: cos-bucket
  region: ap-guangzhou
  protocol: https
  acl:
    permissions: public-read
  cors:
    - maxAgeSeconds: '0'
      allowedMethods:
        - GET
        - PUT
        - POST
      allowedOrigins: '*'
      allowedHeaders: '*'
